name: module3_task0
on: [push, schedule]
- cron: "0 0 * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/SchneiderSix/holbertonschool-validation.git
      make help
