name: module3_task1
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Correct directory and execute the command make help
        working-directory: module3_task1
        run: ./setup.sh
      - name: build
        working-directory: module3_task1
        run: make build
      - name: post
        working-directory: module3_task1
        run: make post POST_NAME=chori POST_TITLE=pan
      - name: help
        working-directory: module3_task1
        run: make help
      - name: clean
        working-directory: module3_task1
        run: make clean
