name: module3_task3
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Install setup
        working-directory: module3_task2
        run: sudo ./setup.sh
      - name: build
        working-directory: module3_task2
        run: make build
      - name: post
        working-directory: module3_task2
        run: make post POST_NAME=chori POST_TITLE=pan
      - name: help
        working-directory: module3_task2
        run: make help
      - name: package
        working-directory: module3_task2
        run: make package
      - name: clean
        working-directory: module3_task2
        run: make clean
      - name: lint
        working-directory: module3_task2
        run: make lint
      - name: unit-tests
        working-directory: module3_task2
        run: make unit-tests
      - name: integration-tests
        working-directory: module3_task2
        run: make integration-tests
      - name: validate
        working-directory: module3_task2
        run: make validate
      - name: arti
        uses: actions/upload-artifact@v3
        with:
          name: line
          path: module3_task2/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module3_task2/awesome-website.zip
            module3_task2/DEPLOY.md
