name: release_drafter

on:
  push:
    branches: 
    - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
          draft: true
      - uses: release-drafter/release-drafter@v5.21.1
        with:
          config-name: chori-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
