name: release_drafter

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5.21.1
        with:
          config-name: chori-drafter.yml
          publish: true
      - uses: actions/upload-artifact@v3
        with:
          name: line
          path: module3_task4/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
