name: release_drafter

on:
  pull_request:
    branches:
      - main
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5.21.1
        with:
          config-name: chori-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
